In [ ]:
#Importando las librerias necesarias para el analisis de la GEIH
import pandas as pd
import numpy as np

In [15]:
#Leyendo los datos de la geih
df_cgsse = pd.read_csv('https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/refs/heads/main/Datos/GEIH2024/CGSSE.CSV'
                       ,encoding='latin',sep=';'
                       )

df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2024/Ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )

/tmp/ipykernel_18008/3051934482.py:6: DtypeWarning: Columns (28,89,135,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2024/Ocupados.CSV'

In [16]:
df_o

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P514,P515,P1881,P1882,P7240,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20240730,7,2024,7858603,1,1,1,60,NaN,2,...,1,1,13,50.0,3,1,480000.0,1,161,9211
1,20240730,7,2024,7858603,1,3,1,60,NaN,2,...,2,1,12,15.0,3,1,640000.0,47,4711,5221
2,20240730,7,2024,7858604,1,1,1,60,NaN,2,...,2,2,3,10.0,8,1,400000.0,47,4781,9520
3,20240730,7,2024,7858604,1,2,1,60,NaN,2,...,1,1,3,20.0,5,1,600000.0,3,312,6222
4,20240730,7,2024,7858605,1,1,1,60,NaN,2,...,1,1,12,25.0,3,1,700000.0,1,161,9211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29924,20240728,7,2024,7889224,1,1,1,60,76.0,1,...,1,1,5,90.0,8,1,1050000.0,97,9700,9111
29925,20240729,7,2024,7889226,1,1,1,60,88.0,1,...,1,1,10,15.0,8,1,3000000.0,77,7729,5249
29926,20240730,7,2024,7889227,1,1,1,60,88.0,1,...,1,1,11,10.0,3,1,1750000.0,61,6110,7422
29927,20240730,7,2024,7889227,1,3,1,60,88.0,1,...,1,1,11,10.0,3,1,2000000.0,55,5511,1411
29928,20240730,7,2024,7889227,1,4,1,60,88.0,1,...,1,1,11,10.0,3,1,1600000.0,55,5511,4224